#
# Attribute map between CS-Studio and Phoebus
# DEFAULT section is shared by all widgets
#
# When to add an attribute map:
# - The Phoebus rendering does not contain the expected attribute name
#
[DEFAULT]
name = "name"
x = "x"
y = "y"
width = "width"
height = "height"
background_color = "background_color"
foreground_color = "foreground_color"
show_grid = "grid_visible"
horizontal_alignment = "horizontal_alignment"
vertical_alignment = "vertical_alignment"
pv_name = "pv_name"
format_type = "format"
enabled = "enabled"
visible = "visible"
scripts = "scripts"
tooltip = "tooltip"

[Line]
line_width = "line_width"
line_style = "line_style"
background_color = "line_color"

[HorizontalLine]
line_width = "line_width"
line_style = "line_style"
background_color = "line_color"

[VerticalLine]
line_width = "line_width"
line_style = "line_style"
background_color = "line_color"

[PointerLine]
line_width = "line_width"
line_style = "line_style"
background_color = "line_color"

[Label]
text = "text"
transparent = "transparent"
rotation_step = "rotation_step"

[TextUpdate]
transparent = "transparent"
show_units = "show_units"
precision = "precision"
rotation_step = "rotation_step"

[TextEntry]
show_units = "show_units"
precision = "precision"

[Spinner]
precision = "precision"
minimum = "minimum"
maximum = "maximum"
show_units = "show_units"
increment = "increment"

[GroupingContainer]
transparent = "transparent"
style = "style"

[ActionButton]
text = "text"
border_alarm_sensitive = "border_alarm_sensitive"
confirm_message = "confirm_message"
show_confirm_dialog = "show_confirm_dialog"
password = "password"
transparent = "transparent"

[ToggleButton]
on_label = "on_label"
off_label = "off_label"

[Byte]
numBits = "numBits"
startBit = "startBit"
on_color = "on_color"
off_color = "off_color"
bitReverse = "bitReverse"

[Led]
on_color = "on_color"
off_color = "off_color"
on_label = "on_label"
off_label = "off_label"
bit = "bit"
square = "square"
line_color = "line_color"

[MultiStateLed]
square = "square"

[EmbeddedContainer]
opi_file = "file"
resize_behaviour = "resize"

[TabbedContainer]
active_tab = "active_tab"
minimum_tab_height = "tab_height"
horizontal_tabs = "direction"

[XYPlot]
show_toolbar = "show_toolbar"
show_legend = "show_legend"

[DataBrowser]
filename = "file"
show_toolbar = "show_toolbar"

[StripChart]
show_toolbar = "show_toolbar"
start = "start"
show_legend = "show_legend"
show_grid = "show_grid"
title_font = "title_font"
scale_font = "scale_font"
label_font = "label_font"

[CheckBox]
label = "label"

[ComboBox]


[ProgressBar]
fill_color = "fill_color"

[LinearMeter]
enable_gradient = "is_gradient_enabled"
highlight_active_region = "is_highlighting_of_active_regions_enabled"
show_units = "show_units"
level_hihi = "level_hihi"
level_high = "level_high"
level_low = "level_low"
level_lolo = "level_lolo"
scale_visible = "scale_visible"

[ScaledSlider]
show_hihi = "show_hihi"
show_high = "show_high"
show_low = "show_low"
show_lolo = "show_lolo"
show_scale = "show_scale"

[SlideButton]
on_color = "on_color"
off_color = "off_color"

[Symbol]
initial_index = "initial_index"
border_alarm_sensitive = "border_alarm_sensitive"

[Table]
show_toolbar = "show_toolbar"

[Polygon]
points = "points"
line_color = "line_color"
line_width = "line_width"
run_actions_on_mouse_click = "run_actions_on_mouse_click"

[Arrow]
points = "points"
line_color = "line_color"

[Rectangle]
line_width = "line_width"
line_color = "line_color"
run_actions_on_mouse_click = "run_actions_on_mouse_click"
